### PR TITLE
Added defaults to preferences

### PR DESCRIPTION
**Pull request by jlampel**
This adds defaults for the relevant properties, including the file name, via context and the add-on preferences.

### CODE REVIEW

**Review by Fweeb — COMMENTED** [review]
Question on the default file path... I see the logic in doing a local folder that's relative the current file... but if the folder doesn't exist, Blender sends the user all the way back to the root of the file system (rather than `//`). Maybe we shouldn't assume that this folder exists and just list the default path as `//`.

Alternatively, we could default to the same path as `bpy.context.preferences.filepaths.asset_libraries[0].path`... that might be handy, particularly if Mark as Asset is true.

**Comment by jlampel** [comment]
Is that when testing on an unsaved file? For me, if the file is saved and the folder doesn't exist, it bumps me back up to `//` anyway. 

Setting the default path to an asset library totally makes sense, but I'm not actually sure how to get that data in the preferences... will try it out tomorrow.

**Comment by Fweeb** [comment]
That was on an unsaved file that I tested on. Silly me for not realizing that.

**Comment by Fweeb** [comment]
> Setting the default path to an asset library totally makes sense, but I'm not actually sure how to get that data in the preferences... will try it out tomorrow.

Quick and dirty way to do this is here:

```
filepath: StringProperty(
    name = 'File Path',
    description = 'Where the export will be saved by default. Use // at the beginning to make it relative to the current blend file',
    default = bpy.context.preferences.filepaths.asset_libraries[0].path
```

It's a bit ugly in that assumes that the first asset library is actually populated, but since that's the default behavior, I *think* that should be OK.

**Comment by jlampel** [comment]
Ok, I got that added! I didn't realize you could use `bpy.context` when defining a property. I made a function that returns the asset library path if it exists and the local path if it does not.

**Pull request merged**
